config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:create]
  end

  resources :bookmarks, only: [:destroy]

  root to: 'lists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie_id, uniqueness: { scope: :list_id }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true

  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  # lists/:id/bookmark/new

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
    @bookmarks = Bookmark.all
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render 'new', status: :unprocessable_entity
    end
  end

private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @lists = List.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>List of all the Lists</h1>

<!-- <ul>
  <% if @lists.any? %>
    <% @lists.each do |list| %>
      <%= link_to list_path(list) do  %>
        <li><%= list.name %></li>
      <% end %>
    <% end %>
  <% else %>
    <li>No lists yet</li>
  <% end %>
</ul> -->

  <div class="cards">
    <% @lists.each do |list| %>
      <%= link_to list_path(list) do %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
          <%= list.name %>
        </div>
      <% end %>
    <% end %>
  </div>


<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Create a movie", class: 'btn btn-primary mt-3' %>
<% end %>

app/views/lists/show.html.erb
<div class="list_banner">
  <h1><%= @list.name %></h1>
</div>

<div class="cards">
  <% @list.bookmarks.each do |bookmark| %>
    <div class="card" style="width: 18rem;">
      <%= image_tag bookmark.movie.poster_url, class: "card-img-top", alt: "#{bookmark.movie.title} poster" %>

      <div class="card-body">
        <h5 class="card-title"><%= bookmark.movie.title %></h5>
        <p class="card-text"><%= truncate(bookmark.movie.overview, length: 120) %></p>
        <div class="bottom d-flex justify-content-between align-items-center">
          <div class="comment"><i class="fa-solid fa-quote-left"></i><p><%= bookmark.comment %></p></div>

          <%= link_to "Delete", list_path(@list),
            # otherwise (not nested): bookmark_path(bookmark),
            data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
            class: "link-danger text-decoration-none" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= link_to lists_path do %>
  <i class="fa-solid fa-house"></i>
<% end %>


<h4>Add a movie to your list</h4>


<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.button :submit %>
<% end %>

app/views/pages/home.html.erb
<div id="hero">
  <div class="container">
    <h1>Save any kind of movies</h1>
    <h3>Your lists, your rules!</h3>
  </div>

</div>

<div class="lists">
  <h3>My Lists</h3>

  <div class="cards">
    <% @lists.each do |list| %>
      <%= link_to list_path(list) do %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
          <%= list.name %>
        </div>
      <% end %>
    <% end %>
  </div>

</div>

<%= link_to "My lists", lists_path %>